import type { SelectOption } from "@/components/SearchableCombobox";

export const VIETNAM_PROVINCES: SelectOption[] = [
  { value: "tuyen-quang", label: "Tuyên Quang" },
  { value: "cao-bang", label: "Cao Bằng" },
  { value: "lai-chau", label: "Lai Châu" },
  { value: "lao-cai", label: "Lào Cai" },
  { value: "thai-nguyen", label: "Thái Nguyên" },
  { value: "dien-bien", label: "Điện Biên" },
  { value: "lang-son", label: "Lạng Sơn" },
  { value: "son-la", label: "Sơn La" },
  { value: "phu-tho", label: "Phú Thọ" },
  { value: "bac-ninh", label: "Bắc Ninh" },
  { value: "quang-ninh", label: "Quảng Ninh" },
  { value: "ha-noi", label: "TP. Hà Nội" },
  { value: "hai-phong", label: "TP. Hải Phòng" },
  { value: "hung-yen", label: "Hưng Yên" },
  { value: "ninh-binh", label: "Ninh Bình" },
  { value: "thanh-hoa", label: "Thanh Hóa" },
  { value: "nghe-an", label: "Nghệ An" },
  { value: "ha-tinh", label: "Hà Tĩnh" },
  { value: "quang-tri", label: "Quảng Trị" },
  { value: "hue", label: "TP. Huế" },
  { value: "da-nang", label: "TP. Đà Nẵng" },
  { value: "quang-ngai", label: "Quảng Ngãi" },
  { value: "gia-lai", label: "Gia Lai" },
  { value: "dak-lak", label: "Đắk Lắk" },
  { value: "khanh-hoa", label: "Khánh Hòa" },
  { value: "lam-dong", label: "Lâm Đồng" },
  { value: "dong-nai", label: "Đồng Nai" },
  { value: "tay-ninh", label: "Tây Ninh" },
  { value: "ho-chi-minh", label: "TP. Hồ Chí Minh" },
  { value: "dong-thap", label: "Đồng Tháp" },
  { value: "an-giang", label: "An Giang" },
  { value: "vinh-long", label: "Vĩnh Long" },
  { value: "can-tho", label: "TP. Cần Thơ" },
  { value: "ca-mau", label: "Cà Mau" },
];
